# Generated by Django 4.2.8 on 2024-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='how_to_get_office',
            field=models.CharField(max_length=512, null=True, verbose_name='Как добраться до офиса'),
        ),
        migrations.AddField(
            model_name='city',
            name='number',
            field=models.BigIntegerField(default=0, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='city',
            name='schedule',
            field=models.TextField(default='Отсутствует', verbose_name='График работы'),
        ),
    ]
