# Generated by Django 4.2.8 on 2024-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_city_how_to_get_office_city_number_city_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Покупатель ли юзер?'),
        ),
    ]
