# Generated by Django 4.2.10 on 2024-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='accusative_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Винительный падеж'),
        ),
        migrations.AddField(
            model_name='city',
            name='dative_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Дательный падеж'),
        ),
        migrations.AddField(
            model_name='city',
            name='genitive_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Родительный падеж'),
        ),
        migrations.AddField(
            model_name='city',
            name='instrumental_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Творительный падеж'),
        ),
        migrations.AddField(
            model_name='city',
            name='nominative_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Именительный падеж'),
        ),
        migrations.AddField(
            model_name='city',
            name='prepositional_case',
            field=models.CharField(max_length=128, null=True, verbose_name='Предложный падеж'),
        )
    ]
