# Generated by Django 4.2.10 on 2024-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['domain'], name='city_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['address'], name='city_address_idx'),
        ),
        migrations.AddIndex(
            model_name='citygroup',
            index=models.Index(fields=['name'], name='citygroup_name_idx'),
        ),
        migrations.AddIndex(
            model_name='citygroup',
            index=models.Index(fields=['main_city'], name='citygroup_main_city_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='customuser_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['city'], name='customuser_city_idx'),
        ),
    ]
