# Generated by Django 4.2.10 on 2024-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_city_accusative_case_city_dative_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
