# Generated by Django 4.2.10 on 2024-02-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_options_city_city_name_idx_and_more'),
        ('account', '0005_alter_customuser_phone'),
    ]

    operations = [
    ]
