# Generated by Django 4.2.11 on 2024-07-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_city_is_active_citygroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='account.citygroup', verbose_name='Группа городов'),
        ),
    ]
