# Generated by Django 4.2.11 on 2024-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_city_city_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Адрес электронной почты', max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
