# Generated by Django 4.2.11 on 2024-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_city_accusative_case_remove_city_dative_case_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citygroup',
            options={'ordering': ('-created_at',), 'verbose_name': 'Группа городов', 'verbose_name_plural': 'Группы городов'},
        ),
    ]
