# Generated by Django 4.2.11 on 2024-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_address_customuser_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citygroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Город'),
        ),
    ]
