# Generated by Django 4.2.11 on 2024-10-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_shedule_store_remove_city_city_address_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('schedule', models.CharField(max_length=256, verbose_name='График работы')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='account.store', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ('store', '-created_at'),
            },
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['title'], name='schedule_title_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule'], name='schedule_schedule_idx'),
        ),
    ]
