# Generated by Django 4.2.11 on 2024-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_schedule_delete_shedule_schedule_schedule_title_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=35.12, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=45.154, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
