# Generated by Django 4.2.11 on 2024-04-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_citygroup_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
