# Generated by Django 4.2.11 on 2024-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citygroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название группы'),
        ),
    ]
