# Generated by Django 4.2.11 on 2024-04-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_citygroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citygroup',
            name='main_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_city_for_group', to='account.city', verbose_name='Главный город'),
        ),
    ]
