# Generated by Django 4.2.11 on 2024-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Численность населения'),
        ),
    ]
