# Generated by Django 4.2.11 on 2024-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='accusative_case',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Винительный падеж'),
        ),
        migrations.AlterField(
            model_name='city',
            name='dative_case',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Дательный падеж'),
        ),
        migrations.AlterField(
            model_name='city',
            name='genitive_case',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Родительный падеж'),
        ),
        migrations.AlterField(
            model_name='city',
            name='instrumental_case',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Творительный падеж'),
        ),
        migrations.AlterField(
            model_name='city',
            name='nominative_case',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Именительный падеж'),
        ),
    ]
