# Generated by Django 4.2.11 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_city_accusative_case_alter_city_dative_case_and_more'),
        ('account', '0019_remove_customuser_customuser_city_idx_and_more'),
    ]

    operations = [
    ]
