# Generated by Django 4.2.11 on 2024-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_merge_20240606_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='In format +7xxxxxxxxxx', max_length=16, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
