# Generated by Django 4.2.11 on 2024-06-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
