stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - backend
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  before_script:
    - docker info
  script:
    - |
      echo "Running tests..."
      docker-compose -f docker-compose-test.yml up -d
      docker-compose exec web python manage.py test --settings=megashop.settings.test
      docker-compose down

deploy:
  stage: deploy
  tags:
    - backend
  only:
    - main
  script:
    - |
      set -x
      echo "Configuring SSH..."
      mkdir -p ~/.ssh/
      echo "$SSH_KEY" > ~/.ssh/gitlab
      chmod 600 ~/.ssh/gitlab
      cat >>~/.ssh/shop-backend-config << END
      Host target-shop
        HostName $SSH_HOST
        User $SSH_USER
        IdentityFile ~/.ssh/gitlab
        LogLevel ERROR
        StrictHostKeyChecking no
      END
      echo "Running deploy..."
      ssh -F ~/.ssh/shop-backend-config target-shop "cd shop-backend/ &&
        docker compose -f docker-compose-traefik.yml down --timeout 30 &&
        git pull https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.altawest.ru/${CI_PROJECT_PATH}.git &&
        docker compose -f docker-compose-traefik.yml build &&
        docker compose -f docker-compose-traefik.yml up -d --force-recreate &&
        docker compose exec web python manage.py migrate --settings=megashop.settings.local"
