stages:
  - cleanup
  - deploy

before_script:
    - |
      set -x
      echo "Configuring SSH..."
      mkdir -p ~/.ssh/
      echo "$SSH_KEY" > ~/.ssh/gitlab
      chmod 600 ~/.ssh/gitlab
      cat >>~/.ssh/config << END
      Host target-shop
        HostName $SSH_HOST
        User $SSH_USER
        IdentityFile ~/.ssh/gitlab
        LogLevel ERROR
        StrictHostKeyChecking no
      END

cleanup:
  stage: cleanup
  script:
    - |
      set -x
      echo "Running Docker cleanup..."
      ssh -i ~/.ssh/gitlab $SSH_USER@$SSH_HOST "cd shop-backend && docker system prune -af"

deploy:
  stage: deploy
  only:
    - main
  script:
    - |
      set -x
      echo "Running deploy..."
      ssh -i ~/.ssh/gitlab $SSH_USER@$SSH_HOST "cd shop-backend/ &&
        docker-compose -f docker-compose-traefik.yml down &&
        git pull https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.altawest.ru/${CI_PROJECT_PATH}.git &&
        docker-compose -f docker-compose-traefik.yml build &&
        docker-compose -f docker-compose-traefik.yml up -d --force-recreate &&
        docker-compose exec web python manage.py migrate --settings=megashop.settings.local"

  dependencies:
    - cleanup
