stages:
  - deploy

variables:
  GITLAB_USER: "valisov"

deploy:
  stage: deploy
  script:
    - |
      set -x
      echo "Configuring SSH..."
      mkdir -p ~/.ssh/
      echo "$SSH_KEY" > ~/.ssh/gitlab
      chmod 600 ~/.ssh/gitlab
      cat >>~/.ssh/config << END
      Host target-shop
        HostName $SSH_HOST
        User $SSH_USER
        IdentityFile ~/.ssh/gitlab
        LogLevel ERROR
        StrictHostKeyChecking no
      END
      echo "Running deploy..."
      ssh target-shop "cd shop-backend/ && docker compose -f docker-compose-traefik.yml down && git pull https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.altawest.ru/${CI_PROJECT_PATH}.git && docker compose -f docker-compose-traefik.yml build && docker compose -f docker-compose-traefik.yml up -d --force-recreate && docker compose exec web python manage.py migrate --settings=megashop.settings.local && docker compose exec web python manage.py migrate --settings=megashop.settings.local && docker compose -f docker-compose-traefik.yml exec web python manage.py search_index --rebuild -y"
