version: '3.8'

services:
  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=megashop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1askas-0gak2m1-,d21p

  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    command: [ "./wait-for-it.sh", "db:5432", "--strict", "--timeout=30", "--", "gunicorn", "--workers=3", "--bind=unix:/code/gunicorn.sock", "megashop.wsgi:application" ]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=megashop.settings.local
      - POSTGRES_DB=megashop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1askas-0gak2m1-,d21p
    depends_on:
      - db

  celery:
    build: .
    command: celery -A celery_config worker --loglevel=info --pool=solo
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=megashop.settings.local
      - POSTGRES_DB=megashop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1askas-0gak2m1-,d21p
    depends_on:
      - db
      - cache

  celerybeat:
    build: .
    command: celery -A celery_config beat --loglevel=debug
    restart: always
    volumes:
      - .:/code
      - ./data/celerybeat:/var/lib/celerybeat  # Папка для хранения файлов состояния планировщика
    environment:
      - DJANGO_SETTINGS_MODULE=megashop.settings.local
      - POSTGRES_DB=megashop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1askas-0gak2m1-,d21p
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./static:/code/static
      - ./media:/code/media
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
