# Generated by Django 4.2.11 on 2024-08-05 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
                ('fields', models.JSONField(unique=True, verbose_name='Поля для экспорта')),
            ],
            options={
                'verbose_name': 'Настройки экспорта',
                'verbose_name_plural': 'Настройки экспорта',
            },
        ),
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидани'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Успешно завершён'), ('FAILED', 'Завершился с ошибкой')], default='PENDING', verbose_name='Статус')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончен')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошбики')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача экспорта',
                'verbose_name_plural': 'Задачи экспорта',
            },
        ),
    ]
