# Generated by Django 4.2.11 on 2024-08-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0002_exporttask_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='export_app.exportsettings', verbose_name='Настройки'),
        ),
    ]
