# Generated by Django 4.2.11 on 2024-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0003_exporttask_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttask',
            name='status',
        ),
        migrations.AddField(
            model_name='exporttask',
            name='export_status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Успешно завершён'), ('FAILED', 'Завершился с ошибкой')], default='PENDING', verbose_name='Статус'),
        ),
    ]
