# Generated by Django 4.2.11 on 2024-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0004_remove_exporttask_status_exporttask_export_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsettings',
            name='fields',
            field=models.JSONField(verbose_name='Поля для экспорта'),
        ),
    ]
