# Generated by Django 4.2.11 on 2024-08-16 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0005_alter_exportsettings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsettings',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Наименование'),
        ),
    ]
