# Generated by Django 4.2.11 on 2024-08-16 08:43

from django.db import migrations, models
from django.utils.text import slugify
from unidecode import unidecode


def generate_slug_for_existing_entries(apps, schema_editor):
    ExportSettings = apps.get_model('export_app', 'ExportSettings')
    for export_setting in ExportSettings.objects.all():
        export_setting.slug = slugify(unidecode(export_setting.name))
        export_setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('export_app', '0006_alter_exportsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsettings',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг', null=True, blank=True),
        ),
        migrations.RunPython(generate_slug_for_existing_entries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exportsettings',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг'),
        ),
    ]
