# Generated by Django 4.2.11 on 2024-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('bitrix_id', models.IntegerField(unique=True, verbose_name='Идентификатор Bitrix24')),
                ('title', models.CharField(max_length=255, verbose_name='Название лида')),
                ('status', models.CharField(max_length=50, verbose_name='Статус лида')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
    ]
