# Generated by Django 4.2.11 on 2024-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_app', '0003_alter_lead_bitrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='dynamical_fields',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
