# Generated by Django 4.2.11 on 2024-11-20 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_hosts',
            field=models.TextField(default='localhost', help_text='Список разрешенных хостов, разделённых запятой', verbose_name='Разрешённые хосты'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Список разрешенных ip адресов, разделённых запятой', null=True, verbose_name='Разрешённые ip адреса'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 10, 1, 20, 80302, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения ключа'),
        ),
    ]
