# Generated by Django 4.2.11 on 2024-12-06 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey_allowed_hosts_apikey_allowed_ips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 6, 11, 41, 51, 281130, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения ключа'),
        ),
    ]
