# Generated by Django 4.2.11 on 2024-12-06 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apikey_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 6, 12, 49, 39, 810597, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения ключа'),
        ),
    ]
