# Generated by Django 4.2.11 on 2024-12-12 13:00

from django.db import migrations
from django.contrib.auth.hashers import make_password


def encrypt_existing_api_keys(apps, schema_editor):
    model = apps.get_model("api", "ApiKey")
    if model.objects.exists():
        for obj in model.objects.all():
            obj.key = make_password(obj.key)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apikey_expires_at'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_api_keys, migrations.RunPython.noop)
    ]
