# Generated by Django 4.2.11 on 2024-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_article_alter_category_thumb_img_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='articles', to='shop.product', verbose_name='Товары'),
        ),
    ]
