# Generated by Django 4.2.11 on 2024-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='articles', to='shop.product', verbose_name='Товары'),
        ),
    ]
