# Generated by Django 4.2.11 on 2024-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('resolved', 'Решено')], default='pending', max_length=20),
        ),
    ]
