# Generated by Django 4.2.11 on 2024-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_feedback_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_at',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
