# Generated by Django 4.2.11 on 2024-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
