# Generated by Django 4.2.11 on 2024-06-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_mainpagesliderimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='tiny_image',
            field=models.ImageField(null=True, upload_to='main/sliders/tiny', verbose_name='Изображение'),
        ),
    ]
