# Generated by Django 4.2.8 on 2024-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_additional_categories_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
