# Generated by Django 4.2.11 on 2024-07-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0004_alter_mainpagesliderimage_tiny_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLMetaTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Шаблон заголовка объекта с подстановкой названия города в разных падежах: 'Купить {object_name} в {prepositional_case}'\nВозможные переменные: object_name, city_group, nominative_case, genitive_case, dative_case, accusative_case, instrumental_case, prepositional_case. (Наименование объекта, название области, ...название города в падежах, начиная с именитольного)", max_length=1024, verbose_name='Заголовок')),
                ('description', models.TextField(help_text="Шаблон описания с подстановкой названия объекта и названия города в разных падежах ()'Купить {object_name} в {city_group}'\nВозможные переменные: object_name, city_group, nominative_case, genitive_case, dative_case, accusative_case, instrumental_case, prepositional_case.(Наименование объекта, название области, ...название города в падежах, начиная с именитольного)", max_length=4096, verbose_name='Описание')),
                ('keywords', models.TextField(help_text="Ключевые слова: 'keyword1, keyword2, keyword3'", max_length=4096, verbose_name='Ключевые слова')),
                ('object_id', models.PositiveIntegerField(verbose_name='Уникальный идентификатор объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тег метаданных',
                'verbose_name_plural': 'Теги метаданных',
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
