# Generated by Django 4.2.11 on 2024-07-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_htmlmetatags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMetaData',
        ),
    ]
