# Generated by Django 4.2.8 on 2024-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видна ли категория (ВЕЗДЕ)'),
        ),
    ]
