# Generated by Django 4.2.11 on 2024-07-17 10:00

from django.db import migrations
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    Model = apps.get_model("shop", "CharacteristicValue")
    duplicates = Model.objects.values('characteristic', 'product').annotate(count=Count("id")).filter(count__gt=1)
    duplicates_ids = []
    for group in duplicates:
        group.pop("count", None)
        duplicates_queryset = Model.objects.filter(**group)
        duplicates_ids.extend(duplicates_queryset.exclude(id=duplicates_queryset.first().id).values_list("id", flat=True))

    Model.objects.filter(id__in=duplicates_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_brand_is_active_category_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='characteristicvalue',
            unique_together={('characteristic', 'product')},
        ),
    ]
