# Generated by Django 4.2.10 on 2024-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Порядковый номер бренда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Порядковый номер категории'),
            preserve_default=False,
        ),
    ]
