# Generated by Django 4.2.10 on 2024-02-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_brand_order_category_order'),
        ('shop', '0010_brand_shop_brand_name_c466ec_idx_and_more'),
    ]

    operations = [
    ]
