# Generated by Django 4.2.11 on 2024-07-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0010_alter_characteristicvalue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='htmlmetatags',
            unique_together={('object_id', 'content_type')},
        ),
    ]
