# Generated by Django 4.2.11 on 2024-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_brand_alter_product_similar_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='key',
        ),
        migrations.AlterField(
            model_name='setting',
            name='predefined_key',
            field=models.CharField(blank=True, choices=[('maintenance', 'Тех. работы'), ('cdn_enabled', 'Включен ли CDN'), ('cdn_address', 'Адрес CDN'), ('multidomains_enabled', 'Включен ли Multidomains'), ('robots_txt', 'Наполнение для robots.txt')], max_length=255, null=True, verbose_name='Предопределенный ключ'),
        ),
    ]
