# Generated by Django 4.2.11 on 2024-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_opengraphmeta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphmeta',
            name='url',
            field=models.CharField(help_text="Ссылка на объект без указания домена пример: '/katalog/vodostochka/dummy-product-2234/'", max_length=255, verbose_name='Ссылка'),
        ),
    ]
