# Generated by Django 4.2.11 on 2024-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_setting_key_alter_setting_predefined_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_image',
            field=models.ImageField(default='', upload_to='catalog/products/', verbose_name='Изображение в каталоге'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='search_image',
            field=models.ImageField(default='', upload_to='catalog/products/', verbose_name='Изображение в поиске'),
            preserve_default=False,
        ),
    ]
