# Generated by Django 4.2.11 on 2024-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_footeritem_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='h1_tag',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='h1 тэг'),
        ),
        migrations.AddField(
            model_name='category',
            name='h1_tag',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='h1 тэг'),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_tag',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='h1 тэг'),
        ),
        migrations.AddField(
            model_name='product',
            name='h1_tag',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='h1 тэг'),
        ),
    ]
