# Generated by Django 4.2.11 on 2024-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
