# Generated by Django 4.2.11 on 2024-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_brand_h1_tag_category_h1_tag_page_h1_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Отзыв'),
        ),
    ]
