# Generated by Django 4.2.11 on 2024-03-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_footer_items', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Настройки Footer',
                'verbose_name_plural': 'Настройки Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('footer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_items', to='shop.footersettings')),
            ],
            options={
                'verbose_name': 'Элемент Footer',
                'verbose_name_plural': 'Элементы Footer',
                'ordering': ['order'],
            },
        ),
    ]
