# Generated by Django 4.2.11 on 2024-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_footersettings_footeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='main/sliders/', verbose_name='Изображение')),
            ],
        ),
    ]
