# Generated by Django 4.2.11 on 2024-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
