# Generated by Django 4.2.11 on 2024-03-25 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_mainpagesliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageCategoryBarItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Категория для панели на главной странице',
                'verbose_name_plural': 'Категории для панели на главной странице',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='mainpagesliderimage',
            options={'ordering': ('order',), 'verbose_name': 'Изображение главной страницы', 'verbose_name_plural': 'Изображения главной страницы'},
        ),
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
