# Generated by Django 4.2.11 on 2024-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_opengraphmeta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='category',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='categories',
            field=models.ManyToManyField(related_name='characteristics', to='shop.category', verbose_name='Категории'),
        ),
    ]
