# Generated by Django 4.2.11 on 2024-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярна ли категория'),
        ),
    ]
