# Generated by Django 4.2.11 on 2024-08-20 08:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(max_length=2048, verbose_name='Описание'),
        ),
    ]
