# Generated by Django 4.2.11 on 2024-03-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='acitve_to',
            new_name='active_to',
        ),
        migrations.AddField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна ли акция'),
        ),
    ]
