# Generated by Django 4.2.11 on 2024-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_acitve_to_promo_active_to_promo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии ли товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярен ли товар'),
        ),
    ]
