# Generated by Django 4.2.11 on 2024-04-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFrequenlyBoughtTogether',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество покупок')),
                ('product_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_from', to='shop.product', verbose_name='Какой товар')),
                ('product_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_to', to='shop.product', verbose_name='Вместе с каким товаром')),
            ],
            options={
                'verbose_name': 'Часто покупают вместе',
                'verbose_name_plural': 'Часто покупают вместе',
                'unique_together': {('product_from', 'product_to')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='frequenly_bought_together',
            field=models.ManyToManyField(blank=True, through='shop.ProductFrequenlyBoughtTogether', to='shop.product', verbose_name='Часто покупают вместе с'),
        ),
    ]
