# Generated by Django 4.2.11 on 2024-08-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0028_page_content_alter_page_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Набор объектов',
                'verbose_name_plural': 'Наборы объектов',
            },
        ),
        migrations.CreateModel(
            name='ItemSetElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID элемента')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='shop.itemset', verbose_name='Набор элементов')),
            ],
            options={
                'verbose_name': 'Элемент набора объектов',
                'verbose_name_plural': 'Элементы набора объектов',
            },
        ),
    ]
