# Generated by Django 4.2.11 on 2024-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_productfrequenlyboughttogether_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagesliderimage',
            name='image_text',
        ),
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
