# Generated by Django 4.2.11 on 2024-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_mainpagesliderimage_image_text_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='footeritem',
            name='column',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер колнки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='footer_settings',
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
    ]
