# Generated by Django 4.2.11 on 2024-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_itemset_itemsetelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemset',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
