# Generated by Django 4.2.11 on 2024-08-23 14:33

from django.db import migrations, models
import django.db.models.deletion
import shop.validators.item_set


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_itemset_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsetelement',
            name='item_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='shop.itemset', validators=[shop.validators.item_set.validate_object_exists], verbose_name='Набор элементов'),
        ),
    ]
