# Generated by Django 4.2.11 on 2024-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_footeritem_footer_settings_footeritem_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeritem',
            name='column',
            field=models.PositiveSmallIntegerField(verbose_name='Номер колонки'),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterUniqueTogether(
            name='footeritem',
            unique_together={('column', 'order')},
        ),
    ]
