# Generated by Django 4.2.11 on 2024-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_footeritem_column_alter_footeritem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='product',
        ),
        migrations.AddField(
            model_name='promo',
            name='categories',
            field=models.ManyToManyField(related_name='promos', to='shop.category', verbose_name='Категории в акции'),
        ),
        migrations.AddField(
            model_name='promo',
            name='products',
            field=models.ManyToManyField(related_name='promos', to='shop.product', verbose_name='Товары в акции'),
        ),
    ]
