# Generated by Django 4.2.11 on 2024-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_promo_category_remove_promo_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBarMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Элемент бокового меню',
                'verbose_name_plural': 'Элементы бокового меню',
                'ordering': ('order',),
            },
        ),
    ]
