# Generated by Django 4.2.11 on 2024-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_itemsetelement_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsetelement',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
