# Generated by Django 4.2.11 on 2024-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_sidebarmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumb_img',
            field=models.TextField(help_text='В кодировке base64 (размера изображения до 10px)', null=True, verbose_name='Миниатюра'),
        ),
    ]
