# Generated by Django 4.2.11 on 2024-08-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0033_itemsetelement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsetelement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
