# Generated by Django 4.2.11 on 2024-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_product_image_remove_productimage_thumb_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb_img',
            field=models.TextField(max_length=512, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='mainpagesliderimage',
            name='thumb_img',
            field=models.TextField(max_length=512, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumb_img',
            field=models.TextField(max_length=512, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumb_img',
            field=models.TextField(max_length=512, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='promo',
            name='thumb_img',
            field=models.TextField(max_length=512, null=True, verbose_name='Миниатюра'),
        ),
    ]
