# Generated by Django 4.2.11 on 2024-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_opengraphmeta_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemset',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Набор объектов', 'verbose_name_plural': 'Наборы объектов'},
        ),
        migrations.AlterField(
            model_name='itemset',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
