# Generated by Django 4.2.11 on 2024-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_itemset_options_alter_itemset_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsetelement',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Элемент набора объектов', 'verbose_name_plural': 'Элементы набора объектов'},
        ),
        migrations.AlterField(
            model_name='itemsetelement',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
