# Generated by Django 4.2.11 on 2024-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_article_alter_category_thumb_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
