# Generated by Django 4.2.11 on 2024-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0037_alter_itemsetelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemset',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsetelement',
            unique_together={('content_type', 'object_id', 'item_set')},
        ),
    ]
