# Generated by Django 4.2.11 on 2024-04-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_address_customuser_region_and_more'),
        ('shop', '0038_productimage_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='price',
            name='shop_price_product_7b3a14_idx',
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='price',
            name='city_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='account.citygroup', verbose_name='Группа городов'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'city_group')},
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'city_group'], name='shop_price_product_ed0f7b_idx'),
        ),
        migrations.RemoveField(
            model_name='price',
            name='city',
        ),
    ]
