# Generated by Django 4.2.11 on 2024-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_price_shop_price_product_7b3a14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmenuitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='sidebar_icons', verbose_name='Изображение'),
        ),
    ]
