# Generated by Django 4.2.11 on 2024-04-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_sidebarmenuitem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.characteristic', verbose_name='Характеристика')),
                ('products', models.ManyToManyField(blank=True, to='shop.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Грпппа продуктов',
                'verbose_name_plural': 'Грпппы продуктов',
                'ordering': ('name',),
            },
        ),
    ]
