# Generated by Django 4.2.11 on 2024-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_productgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumb_img',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='mainpagesliderimage',
            name='thumb_img',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb_img',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb_img',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='thumb_img',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Миниатюра'),
        ),
    ]
