# Generated by Django 4.2.11 on 2024-05-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_category_thumb_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='(Главная страница, возвраты, товар, категория)', max_length=255, unique=True, verbose_name='Наименование страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('site_name', models.CharField(default='Кров маркет', max_length=255, verbose_name='Наименование сайта')),
                ('locale', models.CharField(blank=True, default='ru_RU', help_text='В формате ru_Ru', max_length=10, null=True, verbose_name='Языковой код')),
                ('type', models.CharField(blank=True, default='website', max_length=20, null=True, verbose_name='Тип объекта данных')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категория товаров')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Метаданные OpenGraph',
            },
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(verbose_name='Ссылка')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('open_graph_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='shop.opengraphmeta', verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Изображения метаданных',
            },
        ),
        migrations.AddConstraint(
            model_name='opengraphmeta',
            constraint=models.CheckConstraint(check=models.Q(('category_id__isnull', True), ('product_id__isnull', True), _connector='OR'), name='shop_opengraphmeta_category_product_exclusivity'),
        ),
    ]
