# Generated by Django 4.2.11 on 2024-08-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_itemset_itemset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке')),
                ('image', models.ImageField(upload_to='main/banners', verbose_name='Изображение')),
                ('tiny_image', models.ImageField(null=True, upload_to='main/banners/tiny', verbose_name='Маленькое изображение')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.DeleteModel(
            name='MainPageSliderImage',
        ),
        migrations.AddField(
            model_name='itemset',
            name='grid_type',
            field=models.CharField(blank=True, choices=[('grid_type_1', 'Тип таблицы 1'), ('grid_type_2', 'Тип таблицы 2'), ('grid_type_3', 'Тип таблицы 3'), ('grid_type_4', 'Тип таблицы 4')], help_text="Доступно только для объектов типа 'Баннер'", null=True, verbose_name='Тип таблицы'),
        ),
    ]
