# Generated by Django 4.2.11 on 2024-05-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0043_opengraphmeta_imagemetadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='opengraphmeta',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='opengraphmeta',
            name='shop_opengraphmeta_category_product_exclusivity',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='open_graph_meta',
        ),
        migrations.AlterModelOptions(
            name='imagemetadata',
            options={'verbose_name': 'Изображение метаданных', 'verbose_name_plural': 'Изображения метаданных'},
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='url',
            field=models.CharField(unique=True, verbose_name='Ссылка', max_length=512),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='open_graph_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.opengraphmeta', verbose_name='Метаданные'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='url',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='image',
            field=models.ImageField(default='', upload_to='pages/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='opengraphmeta',
            name='category',
        ),
        migrations.RemoveField(
            model_name='opengraphmeta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='opengraphmeta',
            name='product',
        ),
        migrations.RemoveField(
            model_name='opengraphmeta',
            name='type',
        ),
        migrations.AddField(
            model_name='opengraphmeta',
            name='content_type',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opengraphmeta',
            name='object_id',
            field=models.PositiveIntegerField(default=10, verbose_name='ID объекта'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='opengraphmeta',
            options={'verbose_name': 'Метаданные', 'verbose_name_plural': 'Метаданные'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='Слаг страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение'),
        ),
    ]
