# Generated by Django 4.2.11 on 2024-05-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_page_alter_opengraphmeta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='Исходное изображение'),
        ),
    ]
