# Generated by Django 4.2.11 on 2024-08-28 08:56

import django.core.validators
from django.db import migrations, models
import shop.validators.size_validation


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_banner_delete_mainpagesliderimage_itemset_grid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='main/banners', validators=[shop.validators.size_validation.FileSizeValidator(2), django.core.validators.validate_image_file_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tiny_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/banners/tiny', validators=[shop.validators.size_validation.FileSizeValidator(2), django.core.validators.validate_image_file_extension], verbose_name='Маленькое изображение'),
        ),
    ]
