# Generated by Django 4.2.11 on 2024-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_product_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
