# Generated by Django 4.2.11 on 2024-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_banner_image_alter_banner_tiny_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemset',
            name='grid_type',
            field=models.CharField(blank=True, choices=[('grig-1', 'Тип таблицы 1'), ('grig-2', 'Тип таблицы 2'), ('grig-3', 'Тип таблицы 3'), ('grig-4', 'Тип таблицы 4')], help_text="Доступно только для объектов типа 'Баннер'", null=True, verbose_name='Тип таблицы'),
        ),
    ]
