# Generated by Django 4.2.11 on 2024-08-28 13:34

import django.core.validators
from django.db import migrations, models
import shop.validators.size_validation


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_itemset_grid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке')),
                ('image', models.ImageField(upload_to='main/sliders', validators=[shop.validators.size_validation.FileSizeValidator(2), django.core.validators.validate_image_file_extension], verbose_name='Изображение')),
                ('tiny_image', models.ImageField(blank=True, null=True, upload_to='main/sliders/tiny', validators=[shop.validators.size_validation.FileSizeValidator(2), django.core.validators.validate_image_file_extension], verbose_name='Маленькое изображение')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.AlterField(
            model_name='itemset',
            name='itemset_type',
            field=models.CharField(choices=[('product', 'Товар'), ('banner', 'Баннер'), ('promo', 'Акция'), ('category', 'Категория')], default='product', max_length=64, verbose_name='Тип объектов набора'),
        ),
    ]
