# Generated by Django 4.2.11 on 2024-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_slider_alter_itemset_itemset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка'),
        ),
    ]
