# Generated by Django 4.2.11 on 2024-05-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_characteristic_for_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
