# Generated by Django 4.2.11 on 2024-05-28 11:41

import django.db.models.deletion
from django.db import migrations, models
from django.db import migrations, models
from django.utils.text import slugify
from unidecode import unidecode


def populate_slug(apps, schema_editor):
    CharacteristicValue = apps.get_model('shop', 'CharacteristicValue')
    for cv in CharacteristicValue.objects.all():
        if not cv.slug:
            cv.slug = slugify(unidecode(cv.value))
            cv.save()


class Migration(migrations.Migration):


    dependencies = [
        ('shop', '0048_alter_characteristic_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicvalue',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Слаг', max_length=128),
        ),
        migrations.RunPython(populate_slug),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='slug',
            field=models.SlugField(blank=False, null=False, verbose_name='Слаг', max_length=128),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.characteristic', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='shop.product', verbose_name='Продукт'),
        ),
    ]
