# Generated by Django 4.2.11 on 2024-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_banner_link_alter_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemset',
            name='itemset_type',
            field=models.CharField(choices=[('product', 'Товар'), ('banner', 'Баннер'), ('promo', 'Акция'), ('category', 'Категория'), ('slider', 'Слайдер')], default='product', max_length=64, verbose_name='Тип объектов набора'),
        ),
    ]
