# Generated by Django 4.2.11 on 2024-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_itemset_itemset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphmeta',
            name='description',
            field=models.TextField(help_text="Шаблон описания с подстановкой названия объекта и названия города в разных падежах ()'Купить {object_name} в {cg_loct} по цене {price}'\nВозможные переменные: object_name, price, count, c_nomn, c_gent, c_datv, c_accs, c_ablt, c_loct, cg_nomn, cg_gent, cg_datv, cg_accs, cg_ablt, cg_loct.(Наименование объекта, название области, цена, кол-во товаров в категории ...название города/группы городов в падежах (в формате [c - город / cg - группа городов]_[название падежа (nomn, gent, и т.д.)]), начиная с именитольного)", max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='opengraphmeta',
            name='keywords',
            field=models.TextField(blank=True, help_text="Ключевые слова: 'купить в {c_loct} по цене {price}, сайдинг в {cg_loct}, {object_name} в городе {c_nomn}'. nВозможные переменные: object_name, price, count, c_nomn, c_gent, c_datv, c_accs, c_ablt, c_loct, cg_nomn, cg_gent, cg_datv, cg_accs, cg_ablt, cg_loct. (Наименование объекта, название области, цена, кол-во товаров в категории ...название города/группы городов в падежах (в формате [c - город / cg - группа городов]_[название падежа (nomn, gent, и т.д.)]), начиная с именитольного)", max_length=4096, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='opengraphmeta',
            name='title',
            field=models.CharField(help_text="Шаблон заголовка объекта с подстановкой названия города в разных падежах: 'Купить {object_name} в {c_loct} по цене {price}'\nВозможные переменные: object_name, price, count, c_nomn, c_gent, c_datv, c_accs, c_ablt, c_loct, cg_nomn, cg_gent, cg_datv, cg_accs, cg_ablt, cg_loct. (Наименование объекта, название области, цена, кол-во товаров в категории ...название города/группы городов в падежах (в формате [c - город / cg - группа городов]_[название падежа (nomn, gent, и т.д.)]), начиная с именитольного)", max_length=1024, verbose_name='Заголовок'),
        ),
    ]
