# Generated by Django 4.2.11 on 2024-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_opengraphmeta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphmeta',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование сайта'),
        ),
    ]
