# Generated by Django 4.2.11 on 2024-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_mainpagecategorybaritem_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый ли товар'),
        ),
    ]
