# Generated by Django 4.2.11 on 2024-05-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_product_is_new'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicvalue',
            unique_together={('characteristic', 'product', 'slug')},
        ),
    ]
