# Generated by Django 4.2.11 on 2024-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0052_alter_opengraphmeta_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='predefined_key',
            field=models.CharField(blank=True, choices=[('maintenance', 'Тех. работы'), ('cdn_enabled', 'Включен ли CDN'), ('cdn_address', 'Адрес CDN'), ('multidomains_enabled', 'Включен ли Multidomains'), ('robots_txt', 'Наполнение для robots.txt'), ('openGraphMeta_image', 'Путь до openGraphMeta изображения от корня директории сайта'), ('default_meta_title_template', 'Шаблон по умолчанию для заголовка метаданных'), ('default_meta_description_template', 'Шаблон по умолчанию для описания метаданных'), ('default_meta_keywords_template', 'Шаблон по умолчанию для ключевых слов метаданных')], max_length=255, null=True, verbose_name='Предопределенный ключ'),
        ),
        migrations.AlterUniqueTogether(
            name='opengraphmeta',
            unique_together={('content_type', 'object_id')},
        ),
    ]
