# Generated by Django 4.2.11 on 2024-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_characteristicvalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='delivery, documentation, cart, orders, profile, info', max_length=32, null=True, verbose_name='Заголовок иконки'),
        ),
    ]
