# Generated by Django 4.2.11 on 2024-10-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_categorytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('category_slug', models.SlugField(max_length=256, verbose_name='Слаг целевой категории')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='shop.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Тег категории',
                'verbose_name_plural': 'Теги категорий',
                'ordering': ('name',),
            },
        ),
    ]
