# Generated by Django 4.2.11 on 2024-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_sidebarmenuitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvalue',
            name='slug',
            field=models.SlugField(max_length=1024, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='value',
            field=models.CharField(max_length=1024, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='catalog/products/', verbose_name='Изображение в каталоге'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='catalog/products/', verbose_name='Исходное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='catalog/products/', verbose_name='Изображение в поиске'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='catalog/products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
