# Generated by Django 4.2.11 on 2024-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_categorytag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphmeta',
            name='description',
            field=models.TextField(help_text="Шаблон описания с подстановкой названия объекта и названия города в разных падежах ()'Купить {object_name} в {city_group} по цене {price}'\nВозможные переменные: object_name, city_group, price, count, nomn, gent, datv, accs, ablt, loct.(Наименование объекта, название области, цена, кол-во товаров в категории ...название города в падежах, начиная с именитольного)", max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='opengraphmeta',
            name='keywords',
            field=models.TextField(blank=True, help_text="Ключевые слова: 'купить в {loct} по цене {price}, сайдинг в {city_group}, {object_name} в городе {nomn}'. nВозможные переменные: object_name, city_group, price, count, nomn, gent, datv, accs, ablt, loct. (Наименование объекта, название области, цена, кол-во товаров в категории ...название города в падежах, начиная с именитольного)", max_length=4096, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='opengraphmeta',
            name='title',
            field=models.CharField(help_text="Шаблон заголовка объекта с подстановкой названия города в разных падежах: 'Купить {object_name} в {loct} по цене {price}'\nВозможные переменные: object_name, city_group, price, count, nomn, gent, datv, accs, ablt, loct. (Наименование объекта, название области, цена, кол-во товаров в категории ...название города в падежах, начиная с именитольного)", max_length=1024, verbose_name='Заголовок'),
        ),
    ]
