# Generated by Django 4.2.11 on 2024-06-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_searchhistory'),
        ('shop', '0055_favoriteproduct'),
    ]

    operations = [
    ]
