# Generated by Django 4.2.11 on 2024-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_alter_opengraphmeta_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='predefined_key',
            field=models.CharField(blank=True, choices=[('cdn_address', 'Адрес CDN'), ('maintenance', 'Тех. работы'), ('base_domain', 'Базовый домен'), ('cdn_enabled', 'Включен ли CDN'), ('company_name', 'Наименование компании'), ('robots_txt', 'Наполнение для robots.txt'), ('shop_name', 'Наименование интернет-магазина'), ('default_meta_title_template', 'Шаблон по умолчанию для заголовка метаданных'), ('openGraphMeta_image', 'Путь до openGraphMeta изображения от корня директории сайта'), ('default_meta_keywords_template', 'Шаблон по умолчанию для ключевых слов метаданных'), ('default_meta_description_template', 'Шаблон по умолчанию для описания метаданных')], max_length=255, null=True, verbose_name='Предопределенный ключ'),
        ),
    ]
