# Generated by Django 4.2.11 on 2024-06-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_searchhistory'),
        ('shop', '0055_favoriteproduct'),
        ('shop', '0056_create_productfile_model_and_more'),
    ]

    operations = [
    ]
