# Generated by Django 4.2.11 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_merge_0049_searchhistory_0055_favoriteproduct'),
        ('shop', '0057_merge_20240605_1349'),
    ]

    operations = [
    ]
