# Generated by Django 4.2.11 on 2024-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_setting_predefined_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='шт.', max_length=10, null=True, verbose_name='Единица измерения'),
        ),
    ]
