# Generated by Django 4.2.11 on 2024-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота упаковки (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина упаковки (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес упаковки (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина упаковки (см)'),
        ),
    ]
