# Generated by Django 4.2.11 on 2024-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_merge_20240606_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeritem',
            name='link',
            field=models.CharField(default='#', verbose_name='Ссылка'),
        ),
    ]
