# Generated by Django 4.2.11 on 2024-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_footeritem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promos', to='shop.category', verbose_name='Категории в акции'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promos', to='shop.product', verbose_name='Товары в акции'),
        ),
    ]
