# Generated by Django 4.2.11 on 2024-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_product_package_height_product_package_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='predefined_key',
            field=models.CharField(blank=True, choices=[('cdn_address', 'Адрес CDN'), ('maintenance', 'Тех. работы'), ('base_domain', 'Базовый домен'), ('cdn_enabled', 'Включен ли CDN'), ('company_name', 'Наименование компании'), ('robots_txt', 'Наполнение для robots.txt'), ('shop_name', 'Наименование интернет-магазина'), ('default_meta_title_template', 'Шаблон по умолчанию для заголовка метаданных'), ('openGraphMeta_image', 'Путь до openGraphMeta изображения от корня директории сайта'), ('default_meta_keywords_template', 'Шаблон по умолчанию для ключевых слов метаданных'), ('default_meta_description_template', 'Шаблон по умолчанию для описания метаданных'), ('contact_info', "Контент для страницы 'Контактная информация'")], max_length=255, null=True, verbose_name='Предопределенный ключ'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_string',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Строковое значение'),
        ),
    ]
