# Generated by Django 4.2.11 on 2024-12-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_opengraphmeta_description_and_more'),
        ('shop', '0060_alter_setting_predefined_key_and_more'),
    ]

    operations = [
    ]
