# Generated by Django 4.2.11 on 2024-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0002_alter_importsetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsetting',
            name='inactive_items_action',
            field=models.CharField(choices=[('LEAVE', 'оставить как есть'), ('ACTIVATE', 'активировать')], default='LEAVE', max_length=50, verbose_name='Неактивные объекты'),
        ),
        migrations.AlterField(
            model_name='importsetting',
            name='items_not_in_file_action',
            field=models.CharField(choices=[('DEACTIVATE', 'деактивировать'), ('DELETE', 'удалить'), ('SET_NOT_IN_STOCK', 'установить статус "нет в наличии"'), ('IGNORE', 'не трогать')], default='IGNORE', max_length=50, verbose_name='Объекты не в файле'),
        ),
        migrations.AlterField(
            model_name='importsetting',
            name='remove_existing_price_if_empty',
            field=models.BooleanField(default=False, verbose_name='Удалить существующую цен, если она в файле указана пустой'),
        ),
    ]
