# Generated by Django 4.2.11 on 2024-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0003_alter_importsetting_inactive_items_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsetting',
            name='remove_existing_price_if_empty',
            field=models.BooleanField(default=False, verbose_name='Удалить существующую цену, если она в файле указана пустой'),
        ),
    ]
