# Generated by Django 4.2.11 on 2024-08-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0004_alter_importsetting_remove_existing_price_if_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsetting',
            name='import_task',
        ),
        migrations.AddField(
            model_name='importtask',
            name='import_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='import_app.importsetting', verbose_name='Импорт'),
        ),
    ]
