# Generated by Django 4.2.11 on 2024-08-19 11:14

import django.core.validators
from django.db import migrations, models
import import_app.models
import import_app.validators.import_file


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0005_remove_importsetting_import_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='file',
            field=models.FileField(upload_to=import_app.models.get_default_file_upload_path, validators=[import_app.validators.import_file.size_validate, django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])], verbose_name='Файл импорта'),
        ),
    ]
