# Generated by Django 4.2.11 on 2024-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0006_alter_importtask_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
    ]
