# Generated by Django 4.2.11 on 2024-08-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0007_importtask_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsetting',
            name='remove_existing_price_if_empty',
        ),
    ]
