# Generated by Django 4.2.11 on 2024-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
