# Generated by Django 4.2.11 on 2024-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
