# Generated by Django 4.2.11 on 2024-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_delivery_type_order_receiver_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('address', models.CharField(max_length=512, unique=True, verbose_name='Адрес')),
                ('coord_x', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='X координата')),
                ('coord_y', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Y координата')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
                'unique_together': {('coord_x', 'coord_y')},
            },
        ),
    ]
