# Generated by Django 4.2.11 on 2024-03-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_product'),
        ('cart', '0005_remove_order_address_order_city_name_order_district_and_more'),
    ]

    operations = [
    ]
