# Generated by Django 4.2.11 on 2024-11-14 10:03

from django.conf import settings
from django.db import migrations

def create_default_city(apps, schema_editor):
    City = apps.get_model("account", "City")
    City.objects.get_or_create(name=settings.DEFAULT_CITY_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_pickuppoint'),
    ]

    operations = [
        migrations.RunPython(create_default_city),
    ]
