# Generated by Django 4.2.11 on 2024-12-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_pickuppoint_phone_pickuppointschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pickuppointschedule',
            new_name='pp_schedule_title_idx',
            old_name='schedule_title_idx',
        ),
        migrations.RenameIndex(
            model_name='pickuppointschedule',
            new_name='pp_schedule_schedule_idx',
            old_name='schedule_schedule_idx',
        ),
    ]
