# Generated by Django 4.2.11 on 2024-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
